### ISSUE TITLE
Generalization and scale differences

### ISSUE THREAD

**Issue by fdila** [HpWang-whu/YOHO#10]
I am reading about the generalization capabilities of the backbone.

"Assume the scale difference s between DS and 3DMatch. FCGF is a spatial-voxelization encoder and we set voxel size to 0.025m for 3DMatch in training, thus the voxelized DS should have an similar scale by voxel size a~0.025*s"

What do you mean exactly by the scale difference s?

**Comment by HpWang-whu** [comment]
Hi @fdila,
It means the approximate ratio between the range of your scans over the average range of the 3DMatch scans (~4 meters).

Yours,
