### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by camroo29** [HpWang-whu/YOHO#4]
Would you please provide a guideline on how to implement YOHO with a custom dataset?

**Comment by HpWang-whu** [comment]
Hi, we will provide soon.

**Comment by camroo29** [comment]
Also, it would be great if you explain a bit more about the **gt.log** files. Like how to generate this from the dataset

**Comment by HpWang-whu** [comment]
Sorry for the late reply.
According to the questions in the email:
(1) How to generate gt.log files?
They are offered by the public datasets containing the scan pairs to be evaluated and their ground truth transformations.
To generate such a gt.log, you should (1) determine the scan pairs to use according to their overlap rates (3dmatch use the pairs with overlap>30%, 3dlo use 10%~30%); (2) obtain the ground truth transformation manually. 
More details about gt.log and gt.info can be found in http://redwood-data.org/indoor/registration.html.
(2) Pca_0.3 files are used to filter the plain points in the trainset for less noise. They are eigenvalues calculated by PCA from 0.3m local patches of the keypoints.
They are not used in the testset. 
(3) You can find that in ./others/Readme.md now.

**Comment by camroo29** [comment]
Thank you for the response. After reading your answer and going through the paper what I have understood,
1) for generating the gt.log file, you have utilized the existing registration algorithms (e.g. ICP) to determine the transformation manually. 
2) You have filtered out the planar keypoints based on Eigenvalues calculated by PCA. I still have confusion on how did you apply the threshold (>=0.03) on the Eigenvalues calculated from the PCD data. Would you please give some more details?

Thank you for your time and attention!

**Comment by HpWang-whu** [comment]
Hi,
For more details about PCA-based planar point filter(surface curvature estimation) or surface normal estimation, please refer to https://pcl.readthedocs.io/projects/tutorials/en/master/normal_estimation.html#normal-estimation.
We filter out a point if its surface curvature is smaller than 0.03.

**Comment by camroo29** [comment]
Thank you for your response!
