### ISSUE TITLE
为什么采样的数量是13

### ISSUE THREAD

**Issue by caijillx** [HpWang-whu/YOHO#5]
你好，我注意到在你们的论文和代码中都对群特征在卷积前进行了采样，数量为13。在论文的最后一张表还详细的给出了采样的具体方法。但是我不太明白，为什么是这13种采样方式？这样做的原理是什么？
![image](https://user-images.githubusercontent.com/43942421/162885312-04e7013b-f08d-42e5-920f-f8be503619a1.png)

**Comment by caijillx** [comment]
十分感谢，解释的通俗易懂。我还有一个疑问，文中说表12的每一行代表正二十面体群的一个旋转。但是这标红的13列的数字内容具体是如何推断出的？看上去，其他12列是直接将0-59这60个点，进行12个72度旋转所获得；但正二十面体只有12个顶点，我不明白这其中的对应关系。更为具体的，请问表12是如何生成的？

**Comment by HpWang-whu** [comment]
由于正二十面体群的封闭性，群内任意两个旋转结合仍为群内元素。表12中每个元素（i，j）可以理解为第 i 个群旋转右乘第 j 个群旋转（Rj*Ri）得到的旋转矩阵在群中的索引。第 i 行可以和第一行构建关系，理解为旋转 i 下的群元素顺序变换（例如：索引0的单位阵会变成索引 i ）即Pi。结合证明A.2部分会更好理解。

**Comment by caijillx** [comment]
谢谢！我还想问一下，在你们提供的3dmatch数据集中，包含了cloud_bin_{id}Keypoints.txt，里面存放的是5000个点的序号，请问这些关键点是随机生成的吗，还是你们通过某些方法提取的关键点？

**Comment by HpWang-whu** [comment]
这是官方提供的关键点索引。是随机采样来的。
