### ISSUE TITLE
thanks for your excellent work

### ISSUE THREAD

**Issue by SingularityDog** [HpWang-whu/YOHO#7]
thank you so much,but how to fetch keypoints ?

**Comment by HpWang-whu** [comment]
Hi @SingularityDog ,
Thanks for your interest!
We use 5k randomly-sampled points as keypoints on each scan. The keypoints are the same as that used in FCGF/PerfectMatch/SpinNet.

Sincerely,

**Comment by SingularityDog** [comment]
Is that sampled like farthest point sampling? or completely a random process?

**Comment by SingularityDog** [comment]
already found the answer in another issue,thanks a lot
