### ISSUE TITLE
How should I train my dataset?

### ISSUE THREAD

**Issue by wyaimyj** [HpWang-whu/YOHO#9]
Hello, I would like to use your model to train on my own dataset. My dataset consists of point clouds from different viewpoints of a statue. However, I do not have the corresponding rotation and translation matrices between the point clouds pairwise. How can I address this issue? Thank you!

**Comment by HpWang-whu** [comment]
Hi @wyaimyj,
Thanks for your interest!
To train YOHO on other datasets, you can refer to [here](https://github.com/HpWang-whu/YOHO/blob/master/others/Readme.md).
For multiview reigstration needs, please refer to https://github.com/WHU-USI3DV/SGHR/issues/4#issuecomment-1659680694.
Yours,

**Comment by a1ibekov** [comment]
> Hi @wyaimyj, Thanks for your interest! To train YOHO on other datasets, you can refer to [here](https://github.com/HpWang-whu/YOHO/blob/master/others/Readme.md). For multiview reigstration needs, please refer to [WHU-USI3DV/SGHR#4 (comment)](https://github.com/WHU-USI3DV/SGHR/issues/4#issuecomment-1659680694). Yours,

I have a question on how "cloud_bin_0Keypoints.txt" is created? Thank you!

**Comment by HpWang-whu** [comment]
Hi @a1ibekov,
Thanks for your interest!
'cloud_bin_0Keypoints.txt' contains the point-indexes of 5000 randomly sampled points in 'cloud_bin_0.ply'
Yours,
